### ISSUE TITLE
Where is the test.p file?

### ISSUE THREAD

**Issue by amusi** [hello2all/GTSRB_Keras_STN#3]
I can not find './input/test.p' in test_model.ipynb. I want to know how i can download the file？ thanks

**Comment by hello2all** [comment]
Please refer to the link provided in 'input/download_data.md'

**Comment by amusi** [comment]
Yes，I already read the download_data.md. But i cannot access to "https://d17h27t6h515a5.cloudfront.net/topher/2017/February/5898cd6f_traffic-signs-data/traffic-signs-data.zip". 
Maybe because I'm in China, I can't access this website. 
But I still can't access this site through the wall.
Thank you for your replay~

**Comment by hello2all** [comment]
I've just tested the link and found no issue.

Could you please try again with a VPN connection enabled? A similar issue has been raised before and it turned out that the linked was blocked by the GFW.

Kindly let me know if the issue persists.

**Comment by amusi** [comment]
哈哈，我还是说中文快点。嗯嗯，资源链接应该没问题，我的VPS可能受限，但身边同学的可以下载的。我用迅雷是可以下载的，直接网页打开是不行的。问题解决了，多谢大神

**Comment by amusi** [comment]
顺便问一下，那个.p文件是什么类型的格式？身边人说是MATLAB格式的，我网上查也这么说，请问.p文件是什么，并如何生成的，谢谢啦

**Comment by hello2all** [comment]
*.p 文件是Python的Pickle文件，用来存储变量的。详情看这里：https://docs.python.org/3/library/pickle.html

**Comment by amusi** [comment]
多谢回答。看代码是知道用Pickle读取的，但单独看.p后缀名就有点懵了。好的，再次感谢

**Comment by hello2all** [comment]
不客气
